# Lesson 3
 · Python Fundamentals for Machine Learning
Dataset: **tips2.csv** (restaurant bills and tips)

## 1. Why Google Colab?
- **Free GPUs and TPUs**: ML training, especially deep learning, is resource-intensive. Colab speeds it up without an expensive local GPU or cloud setup.
- **Collaborative**: like Google Docs, several people can edit and run the same notebook.
- **Ready to use**: no installation; popular ML libraries are preinstalled.

Colab is fast, free and collaborative, which makes it ideal for learning, prototyping and small-to-medium experiments.

## 2. Code cells and Markdown cells
| Code cell | Markdown (text) cell |
|---|---|
| Contains Python code | Contains explanations, headings, notes, formulas |
| Executed by Python; output appears below | Rendered as formatted text |

**Markdown syntax:** `# Title` · `## Subtitle` · `### Section` · `**bold**` · `*italic*` · `- list item` · `$y = x^2$`

**Example:**
### ***Formatted section heading***

### Essential shortcuts
| Shortcut | Action |
|---|---|
| `Ctrl + Enter` | Run the current cell |
| `Shift + Enter` | Run and move to the next cell |
| `Ctrl + F9` | Run all cells |
| `Ctrl + M B` | Insert a code cell below |
| `Ctrl + M D` | Delete the current cell |
| `Ctrl + M M` | Convert to Markdown |
| `Ctrl + M Y` | Convert to code |

## 3. Python warm-up

In [5]:
# Import the core data libraries
import numpy as np
import pandas as pd

In [42]:
print('Hello')
print(10 + 5)

Hello
15

In [43]:
# Variables store values under a name
price = 100
discount = 20
final_price = price - discount
print(final_price)

80

In [2]:
salary = 1800
bonus = 200
tax = 100

final_salary = salary + bonus - tax
print(final_salary)

1900

## 4. Loading and exploring the data

In [7]:
# Load the dataset into a DataFrame
df = pd.read_csv("https://raw.githubusercontent.com/HumayDS/E27-120-25-_-Machine-Learning-/refs/heads/main/tips2.csv")
df.head()

   Unnamed: 0  total_bill   tip  gender smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59   NaN  Female     No  Sun  Dinner     4

### Selecting columns and rows

In [8]:
# One column
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [9]:
# Several columns (double brackets)
df[['total_bill', 'gender']]

     total_bill  gender
0         16.99  Female
1         10.34    Male
2         21.01    Male
3         23.68    Male
4         24.59  Female
..          ...     ...
239       29.03    Male
240       27.18  Female
241       22.67    Male
242       17.82    Male
243       18.78  Female

[244 rows x 2 columns]

In [10]:
# Rows 5 to 10 of the selected columns (the end index is excluded)
df[['total_bill', 'gender']].iloc[5:11]

    total_bill gender
5        25.29   Male
6         8.77   Male
7        26.88   Male
8        15.04   Male
9        14.78   Male
10       10.27   Male

In [11]:
# First three rows
df.iloc[0:3]

   Unnamed: 0  total_bill   tip  gender smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3

In [12]:
# First three rows and first two columns
df.iloc[:3, :2]

   Unnamed: 0  total_bill
0           0       16.99
1           1       10.34
2           2       21.01

### Filtering with conditions

In [13]:
# Rows where gender is Female
df[df['gender'] == 'Female']

     Unnamed: 0  total_bill   tip  gender smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
4             4       24.59   NaN  Female     No   Sun  Dinner     4
11           11       35.26  5.00  Female     No   Sun  Dinner     4
14           14       14.83  3.02  Female     No   Sun  Dinner     2
16           16       10.33  1.67  Female     No   Sun  Dinner     3
..          ...         ...   ...     ...    ...   ...     ...   ...
226         226       10.09  2.00  Female    Yes   Fri   Lunch     2
229         229       22.12  2.88  Female    Yes   Sat  Dinner     2
238         238       35.83  4.67  Female     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 8 columns]

In [14]:
# Bills greater than 20
df[df['total_bill'] > 20]

     Unnamed: 0  total_bill   tip  gender smoker  day    time  size
2             2       21.01  3.50    Male     No  Sun  Dinner     3
3             3       23.68  3.31    Male     No  Sun  Dinner     2
4             4       24.59   NaN  Female     No  Sun  Dinner     4
5             5       25.29  4.71    Male     No  Sun  Dinner     4
7             7       26.88  3.12    Male     No  Sun  Dinner     4
..          ...         ...   ...     ...    ...  ...     ...   ...
237         237       32.83  1.17    Male    Yes  Sat  Dinner     2
238         238       35.83  4.67  Female     No  Sat  Dinner     3
239         239       29.03  5.92    Male     No  Sat  Dinner     3
240         240       27.18  2.00  Female    Yes  Sat  Dinner     2
241         241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 8 columns]

In [15]:
# Tips greater than 5
df[df['tip'] > 5]

     Unnamed: 0  total_bill    tip  gender smoker   day    time  size
23           23       39.42   7.58    Male     No   Sat  Dinner     4
24           24       19.82  36.00    Male     No   Sat  Dinner     2
44           44       30.40   5.60    Male     No   Sun  Dinner     4
47           47       32.40   6.00    Male     No   Sun  Dinner     4
52           52       34.81   5.20  Female     No   Sun  Dinner     4
59           59       48.27   6.73    Male     No   Sat  Dinner     4
85           85       34.83   5.17  Female     No  Thur   Lunch     4
88           88       24.71   5.85    Male     No  Thur   Lunch     2
110         110       14.00  42.00    Male     No   Sat  Dinner     2
116         116       29.93   5.07    Male     No   Sun  Dinner     4
141         141       34.30   6.70    Male     No  Thur   Lunch     6
155         155       29.85   5.14  Female     No   Sun  Dinner     5
170         170       50.81  10.00    Male    Yes   Sat  Dinner     3
172         172        7.25   5.15    Male    Yes   Sun  Dinner     2
179         179       34.63  50.00    Male    Yes   Sun  Dinner     2
181         181       23.33   5.65    Male    Yes   Sun  Dinner     2
183         183       23.17   6.50    Male    Yes   Sun  Dinner     4
211         211       25.89   5.16    Male    Yes   Sat  Dinner     4
212         212       48.33   9.00    Male     No   Sat  Dinner     4
214         214       28.17   6.50  Female    Yes   Sat  Dinner     3
239         239       29.03   5.92    Male     No   Sat  Dinner     3

In [16]:
# AND: both conditions must be true
df[(df['gender'] == 'Female') & (df['total_bill'] > 20)]

     Unnamed: 0  total_bill   tip  gender smoker   day    time  size
4             4       24.59   NaN  Female     No   Sun  Dinner     4
11           11       35.26  5.00  Female     No   Sun  Dinner     4
21           21       20.29  2.75  Female     No   Sat  Dinner     2
33           33       20.69  2.45  Female     No   Sat  Dinner     4
52           52       34.81  5.20  Female     No   Sun  Dinner     4
57           57       26.41  1.50  Female     No   Sat  Dinner     2
72           72       26.86  3.14  Female    Yes   Sat  Dinner     2
73           73       25.28  5.00  Female    Yes   Sat  Dinner     2
85           85       34.83  5.17  Female     No  Thur   Lunch     4
94           94       22.75  3.25  Female     No   Fri  Dinner     2
102         102       44.30  2.50  Female    Yes   Sat  Dinner     3
103         103       22.42  3.48  Female    Yes   Sat  Dinner     2
104         104       20.92  4.08  Female     No   Sat  Dinner     2
114         114       25.71  4.00  Female     No   Sun  Dinner     3
119         119       24.08  2.92  Female     No  Thur   Lunch     4
125         125       29.80  4.20  Female     No  Thur   Lunch     6
131         131       20.27  2.83  Female     No  Thur   Lunch     2
143         143       27.05  5.00  Female     No  Thur   Lunch     6
155         155       29.85  5.14  Female     No   Sun  Dinner     5
157         157       25.00  3.75  Female     No   Sun  Dinner     4
186         186       20.90  3.50  Female    Yes   Sun  Dinner     3
197         197       43.11  5.00  Female    Yes  Thur   Lunch     4
214         214       28.17  6.50  Female    Yes   Sat  Dinner     3
219         219       30.14  3.09  Female    Yes   Sat  Dinner     4
229         229       22.12  2.88  Female    Yes   Sat  Dinner     2
238         238       35.83  4.67  Female     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [17]:
# OR: at least one condition must be true
df[(df['gender'] == 'Female') | (df['total_bill'] > 20)]

     Unnamed: 0  total_bill   tip  gender smoker   day    time  size
0             0       16.99  1.01  Female     No   Sun  Dinner     2
2             2       21.01  3.50    Male     No   Sun  Dinner     3
3             3       23.68  3.31    Male     No   Sun  Dinner     2
4             4       24.59   NaN  Female     No   Sun  Dinner     4
5             5       25.29  4.71    Male     No   Sun  Dinner     4
..          ...         ...   ...     ...    ...   ...     ...   ...
238         238       35.83  4.67  Female     No   Sat  Dinner     3
239         239       29.03  5.92    Male     No   Sat  Dinner     3
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2
241         241       22.67  2.00    Male    Yes   Sat  Dinner     2
243         243       18.78  3.00  Female     No  Thur  Dinner     2

[157 rows x 8 columns]

## 5. Data cleaning

### Structure and summary statistics

In [18]:
# Remove the unnecessary index column
df = df.drop("Unnamed: 0", axis=1)

In [19]:
# Column types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         241 non-null    float64
 2   gender      244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [20]:
# Descriptive statistics of numeric columns
df.describe().T

            count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         241.0   3.490415  4.665933  1.00   2.0000   2.920   3.7100  50.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [21]:
# Number of unique values per column
df.nunique()

total_bill    229
tip           122
gender          2
smoker          2
day             4
time            2
size            6
dtype: int64

In [22]:
# Frequency of each category
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [23]:
# Rename a column (displayed only, not saved: no assignment)
df.rename(columns={'day': 'weekday'})

     total_bill   tip  gender smoker weekday    time  size
0         16.99  1.01  Female     No     Sun  Dinner     2
1         10.34  1.66    Male     No     Sun  Dinner     3
2         21.01  3.50    Male     No     Sun  Dinner     3
3         23.68  3.31    Male     No     Sun  Dinner     2
4         24.59   NaN  Female     No     Sun  Dinner     4
..          ...   ...     ...    ...     ...     ...   ...
239       29.03  5.92    Male     No     Sat  Dinner     3
240       27.18  2.00  Female    Yes     Sat  Dinner     2
241       22.67  2.00    Male    Yes     Sat  Dinner     2
242       17.82  1.75    Male     No     Sat  Dinner     2
243       18.78  3.00  Female     No    Thur  Dinner     2

[244 rows x 7 columns]

### Changing data types

In [24]:
# Store categorical columns as 'category'
df['gender'] = df['gender'].astype('category')
df['smoker'] = df['smoker'].astype('category')
df['day'] = df['day'].astype('category')
df['time'] = df['time'].astype('category')
df['size'] = df['size'].astype('int64')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         241 non-null    float64
 2   gender      244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

### Creating a new column and sorting

In [25]:
# New column: bill per person
df["bill_for_1person"] = df["total_bill"] / df["size"]
df.head()

   total_bill   tip  gender smoker  day    time  size  bill_for_1person
0       16.99  1.01  Female     No  Sun  Dinner     2          8.495000
1       10.34  1.66    Male     No  Sun  Dinner     3          3.446667
2       21.01  3.50    Male     No  Sun  Dinner     3          7.003333
3       23.68  3.31    Male     No  Sun  Dinner     2         11.840000
4       24.59   NaN  Female     No  Sun  Dinner     4          6.147500

In [26]:
# Drop the new column
df = df.drop("bill_for_1person", axis=1)

In [27]:
# Highest tips first
df.sort_values(by='tip', ascending=False)

     total_bill   tip  gender smoker   day    time  size
179       34.63  50.0    Male    Yes   Sun  Dinner     2
110       14.00  42.0    Male     No   Sat  Dinner     2
24        19.82  36.0    Male     No   Sat  Dinner     2
170       50.81  10.0    Male    Yes   Sat  Dinner     3
212       48.33   9.0    Male     No   Sat  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
67         3.07   1.0  Female    Yes   Sat  Dinner     1
236       12.60   1.0    Male    Yes   Sat  Dinner     2
4         24.59   NaN  Female     No   Sun  Dinner     4
25        17.81   NaN    Male     No   Sat  Dinner     4
79        17.29   NaN    Male     No  Thur   Lunch     2

[244 rows x 7 columns]

In [28]:
# Maximum and standard deviation of tips
df["tip"].max(), df["tip"].std()

(50.0, 4.665933435777806)

### Missing values

In [29]:
# Number of missing values per column
df.isnull().sum()

total_bill    0
tip           3
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64

In [30]:
# Rows that contain at least one missing value
df[df.isnull().any(axis=1)]

    total_bill  tip  gender smoker   day    time  size
4        24.59  NaN  Female     No   Sun  Dinner     4
25       17.81  NaN    Male     No   Sat  Dinner     4
79       17.29  NaN    Male     No  Thur   Lunch     2

In [31]:
# Remove rows with missing values and check again
df_1 = df.dropna()
df_1.isnull().sum()

total_bill    0
tip           0
gender        0
smoker        0
day           0
time          0
size          0
dtype: int64

In [69]:
#Mean imputation:
#df_2 = df.copy()
#df_2['tip'].fillna(df_2['tip'].mean(), inplace=True)

### Text standardisation and correlation

In [32]:
# .str.upper() → all uppercase, .str.lower() → all lowercase, .str.title() → First Letter Capitalised
df_1['smoker'].str.upper()

0       NO
1       NO
2       NO
3       NO
5       NO
      ...
239     NO
240    YES
241    YES
242     NO
243     NO
Name: smoker, Length: 241, dtype: object

In [33]:
# Correlation between numeric columns
df_1.select_dtypes(include=np.number).corr()

            total_bill       tip      size
total_bill    1.000000  0.247719  0.602282
tip           0.247719  1.000000  0.084956
size          0.602282  0.084956  1.000000

## 6. Outliers: the IQR method
An **outlier** is an unusually high or low value compared with the rest of the data.

- **IQR** (Interquartile Range) = Q3 − Q1
- **Lower fence** = Q1 − 1.5 × IQR
- **Upper fence** = Q3 + 1.5 × IQR

Values outside the fences are outliers.

In [34]:
df_tip = df_1["tip"]
df_tip.describe()

count    241.000000
mean       3.490415
std        4.665933
min        1.000000
25%        2.000000
50%        2.920000
75%        3.710000
max       50.000000
Name: tip, dtype: float64

In [35]:
# Quartiles, IQR and fences
Q1 = df_tip.quantile(0.25)
Q3 = df_tip.quantile(0.75)
IQR = Q3 - Q1

below = Q1 - 1.5 * IQR
above = Q3 + 1.5 * IQR
below, above

(np.float64(-0.565), np.float64(6.275))

In [36]:
# Rows with outlier tips
df_1[df_1["tip"] > above]

     total_bill    tip  gender smoker   day    time  size
23        39.42   7.58    Male     No   Sat  Dinner     4
24        19.82  36.00    Male     No   Sat  Dinner     2
59        48.27   6.73    Male     No   Sat  Dinner     4
110       14.00  42.00    Male     No   Sat  Dinner     2
141       34.30   6.70    Male     No  Thur   Lunch     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
179       34.63  50.00    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3

In [37]:
# Keep only values inside the fences and renumber the rows
clear_df = df_1[df_1["tip"].between(below, above)].reset_index(drop=True)
clear_df['tip'].describe()

count    231.000000
mean       2.857922
std        1.144446
min        1.000000
25%        2.000000
50%        2.740000
75%        3.500000
max        6.000000
Name: tip, dtype: float64

In [38]:
# List all variables in memory
%whos

Variable        Type         Data/Info
--------------------------------------
IQR             float64      1.71
Q1              float64      2.0
Q3              float64      3.71
above           float64      6.275
average         float        80.0
below           float64      -0.565
bonus           int          200
clear_df        DataFrame         total_bill   tip  ge<...>n\n[231 rows x 7 columns]
df              DataFrame         total_bill   tip  ge<...>n\n[244 rows x 7 columns]
df_1            DataFrame         total_bill   tip  ge<...>n\n[241 rows x 7 columns]
df_tip          Series       0      1.01\n1      1.66\<...>ngth: 241, dtype: float64
english_score   int          70
final_salary    int          1900
math_score      int          80
np              module       <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
pd              module       <module 'pandas' from '/u<...>ages/pandas/__init__.py'>
python_score    int          90
salary          int          1800
tax             int          100

In [39]:
# for deleting
del tax

In [41]:
# Import libraries

from sklearn.linear_model import LinearRegression
import numpy as np
import seaborn as sns

# Define independent variables (X) and dependent variable (y)
X = clear_df[['total_bill', 'size']]  # predictors
#X = clear_df.drop('tip', axis=1)
y = clear_df['tip']                   # target

# Create linear regression model
model = LinearRegression()

# Fit model on the entire dataset
model.fit(X, y)

# Make predictions
y_pred = model.predict(X)

# Calculate SSE (Sum of Squared Errors)
sse = np.sum((y - y_pred) ** 2)

# Calculate MSE (Mean Squared Error)
mse = sse / len(y)

# Calculate RMSE (Root Mean Squared Error)
rmse = np.sqrt(mse)

# Print results
print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)
print("SSE:", sse)
print("MSE:", mse)
print("RMSE:", rmse)

# Optional: R^2
r2 = model.score(X, y)
print("R^2 Score:", r2)

Coefficients: [0.07032171 0.20277299]
Intercept: 0.9984325104250864
SSE: 186.31720999401813
MSE: 0.8065680086321131
RMSE: 0.8980913141947834
R^2 Score: 0.3815077323063989

We do train-test splitting in machine learning to evaluate how well our model will perform on new, unseen data.
You split your data into two parts:
Training set → used to teach the model
Test set → used to check how well the model works on new data
Think of it like studying for an exam:
You practice on some questions (train set)
Then the exam has new questions (test set) to see if you really learned.
Usually 70-80% train, 20-30% test.

In [42]:
# Import libraries
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np
import seaborn as sns



# Define features and target
X = clear_df[['total_bill', 'size']]
y = clear_df['tip']

# Split into train and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create linear regression model
model = LinearRegression()

# Train model on training data
model.fit(X_train, y_train)

# Make predictions
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

# Function to calculate SSE, MSE, RMSE, R2
def regression_metrics(y_true, y_pred):
    sse = np.sum((y_true - y_pred)**2)
    mse = sse / len(y_true)
    rmse = np.sqrt(mse)
    r2 = np.corrcoef(y_true, y_pred)[0,1]**2  # alternative: model.score(X, y)
    return sse, mse, rmse, r2

# Calculate metrics for training set
train_sse, train_mse, train_rmse, train_r2 = regression_metrics(y_train, y_train_pred)

# Calculate metrics for test set
test_sse, test_mse, test_rmse, test_r2 = regression_metrics(y_test, y_test_pred)

# Print results
print("=== Training Set ===")
print("SSE:", train_sse)
print("MSE:", train_mse)
print("RMSE:", train_rmse)
print("R^2:", train_r2)

print("\n=== Test Set ===")
print("SSE:", test_sse)
print("MSE:", test_mse)
print("RMSE:", test_rmse)
print("R^2:", test_r2)

=== Training Set ===
SSE: 148.44091905143875
MSE: 0.8067441252795584
RMSE: 0.8981893593666974
R^2: 0.37970140490064214

=== Test Set ===
SSE: 37.99239110727909
MSE: 0.8083487469633849
RMSE: 0.899082169194443
R^2: 0.38615516971272607

## Underfitting
### Definition: Model is too simple to capture the patterns in the data.
###Problem: Poor performance on both training and test data.
###Symptoms: Training error is high
###Test error is also high

###Solution:Icrease model complexity (e.g., add more features, use non-linear models)

#Overfitting
###Definition: Model is too complex and fits the training data too perfectly, including noise.
###Problem: Great performance on training data but poor performance on test/new data.
###Symptoms: Training error is very low
###Test error is high
###Train-test splitting helps detect overfitting: if test error is much higher than training error → overfitting

# Underfitting example:
## RMSE(train) = 4.5
## RMSE(test) = 5.2